// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, name string) (Room, error)
	GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error)
	GetRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
