// Code generated by sqlc. DO NOT EDIT.
// source: room.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
  name,
  creator
) VALUES (
  $1, $2
) RETURNING name, creator, created_at
`

type CreateRoomParams struct {
	Name    string `json:"name"`
	Creator string `json:"creator"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.Name, arg.Creator)
	var i Room
	err := row.Scan(&i.Name, &i.Creator, &i.CreatedAt)
	return i, err
}
